package com.snjewellery.admin.data.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ════════════════════════════════════════════════════════════════════
 *  THE SCHEMA CONTRACT — one of TWO files describing the same tables.
 * ════════════════════════════════════════════════════════════════════
 *
 * The other is `web/lib/data/database.types.ts`, generated by
 * `npm run db:types`. **A schema change is only complete when the
 * migration, that generated file, and this one all change together, in
 * one commit** — CLAUDE.md §3.3. A one-sided change is how two clients
 * in two languages silently stop agreeing, and nothing fails a build to
 * tell you.
 *
 * The full procedure is in `docs/database/schema.md` § "Changing this
 * schema". Step 4 of it is this file.
 *
 * ── What these are, and are not ──────────────────────────────────────
 * These are **row shapes on the wire**: what Postgres returns, named as
 * Postgres names it. They are not the app's domain models. ADR-0007
 * requires repositories to return domain types, so a screen never sees
 * one of these — which is what keeps a column rename from reaching the
 * UI.
 *
 * ── Conventions, and why ─────────────────────────────────────────────
 * **`@SerialName` on every column** whose Postgres name is not already
 * the Kotlin one. Relying on a JSON naming strategy would mean one
 * global setting deciding whether every model still maps, so each field
 * states its own column.
 *
 * **`uuid` maps to `String`.** `kotlin.uuid.Uuid` is still experimental,
 * and these values are only ever passed back to Postgres or used as
 * keys, never constructed or compared as UUIDs.
 *
 * **`timestamptz` maps to `String`**, the ISO-8601 text Postgres sends.
 * Parsing belongs in the mapping to a domain model, where `java.time`
 * is available on every supported version because minSdk is 26. Holding
 * the wire format here keeps this file a faithful mirror rather than an
 * interpretation.
 *
 * **`numeric` maps to `Double`.** Not exact for decimal fractions, and
 * chosen anyway: the website's generated type is `number`, a JS double,
 * so anything else would make the two clients disagree about the same
 * column. Both are well inside the range where a two-decimal value
 * round-trips, and neither client does arithmetic on these — the shop
 * quotes rates to the rupee. **Do not compute money with these**; if
 * that is ever needed, it needs a decimal type on both sides at once.
 *
 * **Defaults are omitted deliberately.** Postgres supplies them, and a
 * Kotlin default would let a row be constructed that the database would
 * have filled differently. Insert payloads are separate types, added by
 * the milestone that first writes (M7).
 */

// ── Enums ────────────────────────────────────────────────────────────
// Structural, not data: adding an aspect means new layout rules, and
// adding a role means new RLS policies. Both are gated by a migration,
// which is what makes them safe to model as closed types here.
// Purities and categories are lookup TABLES for the opposite reason —
// the owner changes them from the app. See schema.md § Enums.

/** Postgres `product_image_aspect`. */
@Serializable
enum class ProductImageAspect {
    @SerialName("product")
    PRODUCT,

    @SerialName("product-portrait")
    PRODUCT_PORTRAIT,
}

/**
 * Postgres `user_role`.
 *
 * `STAFF` is granted nothing today. It exists so that introducing a
 * narrower role later needs new policies rather than a type migration.
 */
@Serializable
enum class UserRole {
    @SerialName("admin")
    ADMIN,

    @SerialName("staff")
    STAFF,
}

/** Postgres `metal`. Exactly two values, permanently — see [MetalRateRow]. */
@Serializable
enum class Metal {
    @SerialName("gold")
    GOLD,

    @SerialName("silver")
    SILVER,
}

// ── Rows ─────────────────────────────────────────────────────────────

/**
 * `categories`. Owner-managed from the app (M8.6).
 *
 * [isVisible] false hides the category **and every product in it** — the
 * policy enforces that, so a query cannot forget it.
 */
@Serializable
data class CategoryRow(
    @SerialName("id") val id: String,
    @SerialName("slug") val slug: String,
    @SerialName("name") val name: String,
    @SerialName("display_order") val displayOrder: Int,
    @SerialName("is_visible") val isVisible: Boolean,
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
)

/**
 * `purities`. A lookup table rather than a constraint, so adding 14K or
 * platinum is one INSERT instead of a migration.
 *
 * **Recorded, not displayed** since the owner's decision of 2026-07-27:
 * the website shows daily [MetalRateRow] instead of per-piece purity.
 * The app still captures it, so this stays.
 */
@Serializable
data class PurityRow(
    @SerialName("id") val id: String,
    /** Short form: `22K`, `18K`, `Silver`. Unique. */
    @SerialName("code") val code: String,
    /** Full form: "22K Gold". */
    @SerialName("label") val label: String,
    @SerialName("display_order") val displayOrder: Int,
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
)

/**
 * `products`.
 *
 * Three flags that are easy to confuse, and the policies treat them
 * differently:
 * - [sold] — **stays visible** to customers, with a badge.
 * - [archived] — hidden from customers, still listed in the app.
 * - [featured] — home page.
 */
@Serializable
data class ProductRow(
    @SerialName("id") val id: String,
    /** Unique, kebab-case. Generated at upload (M7.11); SEO URLs. */
    @SerialName("slug") val slug: String,
    @SerialName("name") val name: String,
    /** Short form, for cards. */
    @SerialName("summary") val summary: String? = null,
    /** Full form, for the product page. */
    @SerialName("description") val description: String? = null,
    /** FK → `categories`. **ON DELETE RESTRICT** — see schema.md. */
    @SerialName("category_id") val categoryId: String,
    /** FK → `purities`. Recorded, not displayed. */
    @SerialName("purity_id") val purityId: String? = null,
    /** Grams. Recorded, not displayed. See the `numeric` note above. */
    @SerialName("weight_grams") val weightGrams: Double? = null,
    @SerialName("colours") val colours: List<String>,
    /** Searchable in M10. GIN indexed. */
    @SerialName("tags") val tags: List<String>,
    @SerialName("featured") val featured: Boolean,
    @SerialName("sold") val sold: Boolean,
    @SerialName("archived") val archived: Boolean,
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
)

/**
 * `product_images`.
 *
 * Deleting a product cascades to these rows but **not** to the storage
 * objects. M8.4 deletes both explicitly; orphans cost money silently.
 */
@Serializable
data class ProductImageRow(
    @SerialName("id") val id: String,
    /** FK → `products`. ON DELETE CASCADE. */
    @SerialName("product_id") val productId: String,
    /** Public CDN URL. */
    @SerialName("url") val url: String,
    /** Path in the bucket, so renditions can be derived (ADR-0005). */
    @SerialName("storage_path") val storagePath: String,
    /** Zero-based, unique per product. Position 0 is the primary image. */
    @SerialName("display_order") val displayOrder: Int,
    @SerialName("aspect") val aspect: ProductImageAspect,
    @SerialName("created_at") val createdAt: String,
)

/**
 * `metal_rates`. Today's rate per gram, set by the owner each morning.
 *
 * **Exactly two rows, permanently.** The metal is the primary key and an
 * enum of two values, so a third rate, a duplicate, and a missing row
 * are all impossible. There is no INSERT and no DELETE policy for
 * anyone, admins included — the shape of this table is not something a
 * client may change.
 *
 * [ratePerGram] and [updatedAt] are null or non-null **together**,
 * enforced by a CHECK and a trigger rather than by callers remembering.
 * A timestamp outliving the number it describes would tell a customer a
 * stale rate was set this morning. Null means *not published yet*, and
 * the website hides the panel entirely until both metals are set.
 */
@Serializable
data class MetalRateRow(
    @SerialName("metal") val metal: Metal,
    /** Rupees per gram. Null until published. See the `numeric` note. */
    @SerialName("rate_per_gram") val ratePerGram: Double? = null,
    /** Null while unpublished; set by trigger. */
    @SerialName("updated_at") val updatedAt: String? = null,
)

/**
 * `users`. Mirrors `auth.users`; a row is created by the
 * `on_auth_user_created` trigger, defaulting to `admin`, because public
 * signup is disabled and every account is created deliberately.
 *
 * [role] is **not self-assignable** — the policy forbids it, and M6.9's
 * role gate reads it rather than trusting anything the client holds.
 */
@Serializable
data class UserRow(
    /** PK, FK → `auth.users`. ON DELETE CASCADE. */
    @SerialName("id") val id: String,
    @SerialName("name") val name: String? = null,
    @SerialName("email") val email: String? = null,
    @SerialName("role") val role: UserRole,
    @SerialName("created_at") val createdAt: String,
    @SerialName("updated_at") val updatedAt: String,
)
